# Generated by Django 3.0.3 on 2020-02-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('OB', 'Observational/Assessment'), ('LT', 'Long Term Goal'), ('ST', 'Short Term Goal'), ('TI', 'Therapeutic Intervention'), ('CP', 'Client Progress'), ('PL', 'Plan for Next Session')], default='OB', max_length=2)),
                ('description', models.TextField()),
                ('clientPresentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment_plan.ClientPresentation')),
            ],
        ),
    ]
