# Generated by Django 3.0.3 on 2020-03-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(choices=[('OB', 'Observation/Assessment'), ('LT', 'Long Term Goal'), ('ST', 'Short Term Objective'), ('TI', 'Therapeutic Intervention'), ('CP', 'Client Progress'), ('PL', 'Plan for Next Session')], default='OB', max_length=2),
        ),
    ]
