# Generated by Django 3.0.4 on 2020-04-19 22:31

from django.db import migrations, models
import django.db.models.deletion
import treatment_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_plan', '0002_auto_20200313_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('resource_type', models.CharField(choices=[('VD', 'Video'), ('DT', 'Document')], default='VD', max_length=2)),
                ('path', models.FileField(upload_to=treatment_plan.models.get_upload_path)),
                ('URL', models.TextField(blank=True)),
                ('ClientPresentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment_plan.ClientPresentation')),
            ],
        ),
    ]
