# Generated by Django 3.0.4 on 2020-04-21 03:06

from django.db import migrations, models
import treatment_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_plan', '0004_auto_20200420_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalresource',
            name='path',
            field=models.FileField(blank=True, upload_to=treatment_plan.models.get_upload_path),
        ),
    ]
